from .schemas import (
    Alignment,
    Bar,
    FeatureSpec,
    OverlayObject,
    ReviewVerdict,
    StructureObject,
    StructureState,
)

__all__ = [
    "Alignment",
    "BAR_ARTIFACT_COLUMNS",
    "BAR_ARRAY_COLUMNS",
    "Bar",
    "BarArtifactManifest",
    "BarArrays",
    "CANONICAL_BAR_COLUMNS",
    "CanonicalBarIngestionConfig",
    "EDGE_FEATURE_KEYS",
    "EDGE_FEATURE_VERSION",
    "FEATURE_BUNDLE_BASE_COLUMNS",
    "EMPTY_FEATURE_PARAMS",
    "EMPTY_FEATURE_PARAMS_HASH",
    "FEATURE_ARTIFACT_COLUMNS",
    "FeatureSpec",
    "FeatureArtifactManifest",
    "STRUCTURE_ARTIFACT_COLUMNS",
    "StructureArtifactManifest",
    "EdgeFeatureMaterializationConfig",
    "OverlayObject",
    "PIVOT_KIND_GROUP",
    "PIVOT_LEFT_WINDOW",
    "PIVOT_RIGHT_WINDOW",
    "PIVOT_RULEBOOK_VERSION",
    "PIVOT_STRUCTURE_VERSION",
    "PivotMaterializationConfig",
    "PivotScanResult",
    "ReviewVerdict",
    "StructureObject",
    "StructureState",
    "bar_arrays_from_frame",
    "build_bar_data_version",
    "build_feature_ref",
    "build_feature_params_hash",
    "build_initial_edge_feature_specs",
    "build_pivot_structure_frame",
    "build_structure_id",
    "build_structure_input_ref",
    "compute_pivot_scan",
    "compute_pivot_scan_reference",
    "frame_to_structure_objects",
    "list_bar_data_versions",
    "list_feature_keys",
    "list_structure_kinds",
    "load_bar_arrays",
    "load_bar_manifest",
    "load_canonical_bars",
    "load_feature_artifact",
    "load_feature_bundle",
    "load_feature_manifest",
    "load_structure_artifact",
    "load_structure_bundle",
    "load_structure_inputs",
    "load_structure_manifest",
    "load_structure_objects",
    "materialize_initial_edge_features",
    "materialize_pivots",
    "materialize_canonical_bars",
    "compute_initial_edge_feature_bundle",
]


def __getattr__(name: str):
    if name in {
        "BAR_ARTIFACT_COLUMNS",
        "BarArtifactManifest",
        "EMPTY_FEATURE_PARAMS",
        "EMPTY_FEATURE_PARAMS_HASH",
        "FEATURE_ARTIFACT_COLUMNS",
        "FeatureArtifactManifest",
        "STRUCTURE_ARTIFACT_COLUMNS",
        "StructureArtifactManifest",
        "build_bar_data_version",
        "build_feature_params_hash",
        "frame_to_structure_objects",
        "list_bar_data_versions",
        "list_feature_keys",
        "list_structure_kinds",
        "load_bar_manifest",
        "load_canonical_bars",
        "load_feature_artifact",
        "load_feature_bundle",
        "load_feature_manifest",
        "load_structure_artifact",
        "load_structure_bundle",
        "load_structure_manifest",
        "load_structure_objects",
    }:
        from .artifacts import (
            BAR_ARTIFACT_COLUMNS,
            BarArtifactManifest,
            EMPTY_FEATURE_PARAMS,
            EMPTY_FEATURE_PARAMS_HASH,
            FEATURE_ARTIFACT_COLUMNS,
            FeatureArtifactManifest,
            STRUCTURE_ARTIFACT_COLUMNS,
            StructureArtifactManifest,
            build_bar_data_version,
            build_feature_params_hash,
            frame_to_structure_objects,
            list_bar_data_versions,
            list_feature_keys,
            list_structure_kinds,
            load_bar_manifest,
            load_canonical_bars,
            load_feature_artifact,
            load_feature_bundle,
            load_feature_manifest,
            load_structure_artifact,
            load_structure_bundle,
            load_structure_manifest,
            load_structure_objects,
        )

        exports = {
            "BAR_ARTIFACT_COLUMNS": BAR_ARTIFACT_COLUMNS,
            "BarArtifactManifest": BarArtifactManifest,
            "EMPTY_FEATURE_PARAMS": EMPTY_FEATURE_PARAMS,
            "EMPTY_FEATURE_PARAMS_HASH": EMPTY_FEATURE_PARAMS_HASH,
            "FEATURE_ARTIFACT_COLUMNS": FEATURE_ARTIFACT_COLUMNS,
            "FeatureArtifactManifest": FeatureArtifactManifest,
            "STRUCTURE_ARTIFACT_COLUMNS": STRUCTURE_ARTIFACT_COLUMNS,
            "StructureArtifactManifest": StructureArtifactManifest,
            "build_bar_data_version": build_bar_data_version,
            "build_feature_params_hash": build_feature_params_hash,
            "frame_to_structure_objects": frame_to_structure_objects,
            "list_bar_data_versions": list_bar_data_versions,
            "list_feature_keys": list_feature_keys,
            "list_structure_kinds": list_structure_kinds,
            "load_bar_manifest": load_bar_manifest,
            "load_canonical_bars": load_canonical_bars,
            "load_feature_artifact": load_feature_artifact,
            "load_feature_bundle": load_feature_bundle,
            "load_feature_manifest": load_feature_manifest,
            "load_structure_artifact": load_structure_artifact,
            "load_structure_bundle": load_structure_bundle,
            "load_structure_manifest": load_structure_manifest,
            "load_structure_objects": load_structure_objects,
        }
        return exports[name]

    if name in {
        "BAR_ARRAY_COLUMNS",
        "BarArrays",
        "CANONICAL_BAR_COLUMNS",
        "CanonicalBarIngestionConfig",
        "bar_arrays_from_frame",
        "load_bar_arrays",
        "materialize_canonical_bars",
    }:
        from .data import (
            BAR_ARRAY_COLUMNS,
            BarArrays,
            CANONICAL_BAR_COLUMNS,
            CanonicalBarIngestionConfig,
            bar_arrays_from_frame,
            load_bar_arrays,
            materialize_canonical_bars,
        )

        exports = {
            "BAR_ARRAY_COLUMNS": BAR_ARRAY_COLUMNS,
            "BarArrays": BarArrays,
            "CANONICAL_BAR_COLUMNS": CANONICAL_BAR_COLUMNS,
            "CanonicalBarIngestionConfig": CanonicalBarIngestionConfig,
            "bar_arrays_from_frame": bar_arrays_from_frame,
            "load_bar_arrays": load_bar_arrays,
            "materialize_canonical_bars": materialize_canonical_bars,
        }
        return exports[name]

    if name in {
        "EDGE_FEATURE_KEYS",
        "EDGE_FEATURE_VERSION",
        "EdgeFeatureMaterializationConfig",
        "build_initial_edge_feature_specs",
        "compute_initial_edge_feature_bundle",
        "materialize_initial_edge_features",
    }:
        from .features import (
            EDGE_FEATURE_KEYS,
            EDGE_FEATURE_VERSION,
            EdgeFeatureMaterializationConfig,
            build_initial_edge_feature_specs,
            compute_initial_edge_feature_bundle,
            materialize_initial_edge_features,
        )

        exports = {
            "EDGE_FEATURE_KEYS": EDGE_FEATURE_KEYS,
            "EDGE_FEATURE_VERSION": EDGE_FEATURE_VERSION,
            "EdgeFeatureMaterializationConfig": EdgeFeatureMaterializationConfig,
            "build_initial_edge_feature_specs": build_initial_edge_feature_specs,
            "compute_initial_edge_feature_bundle": compute_initial_edge_feature_bundle,
            "materialize_initial_edge_features": materialize_initial_edge_features,
        }
        return exports[name]

    if name in {
        "FEATURE_BUNDLE_BASE_COLUMNS",
        "PIVOT_KIND_GROUP",
        "PIVOT_LEFT_WINDOW",
        "PIVOT_RIGHT_WINDOW",
        "PIVOT_RULEBOOK_VERSION",
        "PIVOT_STRUCTURE_VERSION",
        "PivotMaterializationConfig",
        "PivotScanResult",
        "build_feature_ref",
        "build_pivot_structure_frame",
        "build_structure_id",
        "build_structure_input_ref",
        "compute_pivot_scan",
        "compute_pivot_scan_reference",
        "load_structure_inputs",
        "materialize_pivots",
    }:
        from .structures import (
            FEATURE_BUNDLE_BASE_COLUMNS,
            PIVOT_KIND_GROUP,
            PIVOT_LEFT_WINDOW,
            PIVOT_RIGHT_WINDOW,
            PIVOT_RULEBOOK_VERSION,
            PIVOT_STRUCTURE_VERSION,
            PivotMaterializationConfig,
            PivotScanResult,
            build_feature_ref,
            build_pivot_structure_frame,
            build_structure_id,
            build_structure_input_ref,
            compute_pivot_scan,
            compute_pivot_scan_reference,
            load_structure_inputs,
            materialize_pivots,
        )

        exports = {
            "FEATURE_BUNDLE_BASE_COLUMNS": FEATURE_BUNDLE_BASE_COLUMNS,
            "PIVOT_KIND_GROUP": PIVOT_KIND_GROUP,
            "PIVOT_LEFT_WINDOW": PIVOT_LEFT_WINDOW,
            "PIVOT_RIGHT_WINDOW": PIVOT_RIGHT_WINDOW,
            "PIVOT_RULEBOOK_VERSION": PIVOT_RULEBOOK_VERSION,
            "PIVOT_STRUCTURE_VERSION": PIVOT_STRUCTURE_VERSION,
            "PivotMaterializationConfig": PivotMaterializationConfig,
            "PivotScanResult": PivotScanResult,
            "build_feature_ref": build_feature_ref,
            "build_pivot_structure_frame": build_pivot_structure_frame,
            "build_structure_id": build_structure_id,
            "build_structure_input_ref": build_structure_input_ref,
            "compute_pivot_scan": compute_pivot_scan,
            "compute_pivot_scan_reference": compute_pivot_scan_reference,
            "load_structure_inputs": load_structure_inputs,
            "materialize_pivots": materialize_pivots,
        }
        return exports[name]

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
