from .schemas import (
    Alignment,
    Bar,
    FeatureSpec,
    OverlayObject,
    ResolvedStructureState,
    ReviewVerdict,
    StructureEventType,
    StructureLifecycleEvent,
    StructureObject,
    StructureState,
)

__all__ = [
    "Alignment",
    "BAR_ARTIFACT_COLUMNS",
    "BAR_ARRAY_COLUMNS",
    "Bar",
    "BarArtifactManifest",
    "BarArrays",
    "CANONICAL_BAR_COLUMNS",
    "CanonicalBarIngestionConfig",
    "EDGE_FEATURE_KEYS",
    "EDGE_FEATURE_VERSION",
    "EMA_BAR_FINALIZATION",
    "EMA_DTYPE",
    "EMA_FEATURE_KEY",
    "EMA_FEATURE_VERSION",
    "EMA_SOURCE_FIELD",
    "EMA_TIMING_SEMANTICS",
    "EMA_WARMUP_MULTIPLIER",
    "EMPTY_FEATURE_PARAMS",
    "EMPTY_FEATURE_PARAMS_HASH",
    "FEATURE_ARTIFACT_COLUMNS",
    "FEATURE_BUNDLE_BASE_COLUMNS",
    "FeatureArtifactManifest",
    "FeatureSpec",
    "LEG_BAR_FINALIZATION",
    "LEG_KIND_GROUP",
    "LEG_RULEBOOK_VERSION",
    "LEG_STRUCTURE_VERSION",
    "LEG_TIMING_SEMANTICS",
    "LegMaterializationConfig",
    "MAJOR_LH_BAR_FINALIZATION",
    "MAJOR_LH_KIND_GROUP",
    "MAJOR_LH_RULEBOOK_VERSION",
    "MAJOR_LH_STRUCTURE_VERSION",
    "MAJOR_LH_TIMING_SEMANTICS",
    "MVP_OVERLAY_DATASET_KINDS",
    "MVP_OVERLAY_VERSION",
    "MajorLowerHighMaterializationConfig",
    "OverlayObject",
    "PIVOT_KIND_GROUP",
    "PIVOT_LEFT_WINDOW",
    "PIVOT_RIGHT_WINDOW",
    "PIVOT_RULEBOOK_VERSION",
    "PIVOT_STRUCTURE_VERSION",
    "PivotMaterializationConfig",
    "PivotScanResult",
    "ResolvedStructureState",
    "ReviewVerdict",
    "STRUCTURE_ARTIFACT_COLUMNS",
    "StructureArtifactManifest",
    "StructureDependency",
    "StructureEventType",
    "StructureLifecycleEvent",
    "StructureObject",
    "StructureState",
    "bar_arrays_from_frame",
    "build_bar_data_version",
    "build_ema_feature_spec",
    "build_event_overlay_id",
    "build_feature_params_hash",
    "build_feature_ref",
    "build_initial_edge_feature_specs",
    "build_leg_structure_frame",
    "build_major_lh_structure_frame",
    "build_overlay_id",
    "build_pivot_structure_frame",
    "build_structure_id",
    "build_structure_input_ref",
    "build_structure_ref",
    "compute_ema_values",
    "compute_initial_edge_feature_bundle",
    "compute_pivot_scan",
    "compute_pivot_scan_reference",
    "ema_warmup_bars",
    "frame_to_structure_objects",
    "list_bar_data_versions",
    "list_feature_keys",
    "list_structure_kinds",
    "load_bar_arrays",
    "load_bar_manifest",
    "load_canonical_bars",
    "load_feature_artifact",
    "load_feature_bundle",
    "load_feature_manifest",
    "load_structure_artifact",
    "load_structure_bundle",
    "load_structure_dependency",
    "load_structure_inputs",
    "load_structure_manifest",
    "load_structure_objects",
    "materialize_canonical_bars",
    "materialize_initial_edge_features",
    "materialize_legs",
    "materialize_major_lh",
    "materialize_pivots",
    "normalize_ema_lengths",
    "overlay_hit_test_priority",
    "overlay_z_order",
    "project_overlay_objects",
    "project_structure_event_overlay_objects",
    "sort_overlay_objects_for_render",
]


def __getattr__(name: str):
    if name in {
        "BAR_ARTIFACT_COLUMNS",
        "BarArtifactManifest",
        "EMPTY_FEATURE_PARAMS",
        "EMPTY_FEATURE_PARAMS_HASH",
        "FEATURE_ARTIFACT_COLUMNS",
        "FeatureArtifactManifest",
        "STRUCTURE_ARTIFACT_COLUMNS",
        "StructureArtifactManifest",
        "build_bar_data_version",
        "build_feature_params_hash",
        "frame_to_structure_objects",
        "list_bar_data_versions",
        "list_feature_keys",
        "list_structure_kinds",
        "load_bar_manifest",
        "load_canonical_bars",
        "load_feature_artifact",
        "load_feature_bundle",
        "load_feature_manifest",
        "load_structure_artifact",
        "load_structure_bundle",
        "load_structure_manifest",
        "load_structure_objects",
    }:
        from .artifacts import (
            BAR_ARTIFACT_COLUMNS,
            BarArtifactManifest,
            EMPTY_FEATURE_PARAMS,
            EMPTY_FEATURE_PARAMS_HASH,
            FEATURE_ARTIFACT_COLUMNS,
            FeatureArtifactManifest,
            STRUCTURE_ARTIFACT_COLUMNS,
            StructureArtifactManifest,
            build_bar_data_version,
            build_feature_params_hash,
            frame_to_structure_objects,
            list_bar_data_versions,
            list_feature_keys,
            list_structure_kinds,
            load_bar_manifest,
            load_canonical_bars,
            load_feature_artifact,
            load_feature_bundle,
            load_feature_manifest,
            load_structure_artifact,
            load_structure_bundle,
            load_structure_manifest,
            load_structure_objects,
        )

        exports = {
            "BAR_ARTIFACT_COLUMNS": BAR_ARTIFACT_COLUMNS,
            "BarArtifactManifest": BarArtifactManifest,
            "EMPTY_FEATURE_PARAMS": EMPTY_FEATURE_PARAMS,
            "EMPTY_FEATURE_PARAMS_HASH": EMPTY_FEATURE_PARAMS_HASH,
            "FEATURE_ARTIFACT_COLUMNS": FEATURE_ARTIFACT_COLUMNS,
            "FeatureArtifactManifest": FeatureArtifactManifest,
            "STRUCTURE_ARTIFACT_COLUMNS": STRUCTURE_ARTIFACT_COLUMNS,
            "StructureArtifactManifest": StructureArtifactManifest,
            "build_bar_data_version": build_bar_data_version,
            "build_feature_params_hash": build_feature_params_hash,
            "frame_to_structure_objects": frame_to_structure_objects,
            "list_bar_data_versions": list_bar_data_versions,
            "list_feature_keys": list_feature_keys,
            "list_structure_kinds": list_structure_kinds,
            "load_bar_manifest": load_bar_manifest,
            "load_canonical_bars": load_canonical_bars,
            "load_feature_artifact": load_feature_artifact,
            "load_feature_bundle": load_feature_bundle,
            "load_feature_manifest": load_feature_manifest,
            "load_structure_artifact": load_structure_artifact,
            "load_structure_bundle": load_structure_bundle,
            "load_structure_manifest": load_structure_manifest,
            "load_structure_objects": load_structure_objects,
        }
        return exports[name]

    if name in {
        "BAR_ARRAY_COLUMNS",
        "BarArrays",
        "CANONICAL_BAR_COLUMNS",
        "CanonicalBarIngestionConfig",
        "bar_arrays_from_frame",
        "load_bar_arrays",
        "materialize_canonical_bars",
    }:
        from .data import (
            BAR_ARRAY_COLUMNS,
            BarArrays,
            CANONICAL_BAR_COLUMNS,
            CanonicalBarIngestionConfig,
            bar_arrays_from_frame,
            load_bar_arrays,
            materialize_canonical_bars,
        )

        exports = {
            "BAR_ARRAY_COLUMNS": BAR_ARRAY_COLUMNS,
            "BarArrays": BarArrays,
            "CANONICAL_BAR_COLUMNS": CANONICAL_BAR_COLUMNS,
            "CanonicalBarIngestionConfig": CanonicalBarIngestionConfig,
            "bar_arrays_from_frame": bar_arrays_from_frame,
            "load_bar_arrays": load_bar_arrays,
            "materialize_canonical_bars": materialize_canonical_bars,
        }
        return exports[name]

    if name in {
        "EDGE_FEATURE_KEYS",
        "EDGE_FEATURE_VERSION",
        "EMA_BAR_FINALIZATION",
        "EMA_DTYPE",
        "EMA_FEATURE_KEY",
        "EMA_FEATURE_VERSION",
        "EMA_SOURCE_FIELD",
        "EMA_TIMING_SEMANTICS",
        "EMA_WARMUP_MULTIPLIER",
        "EdgeFeatureMaterializationConfig",
        "build_ema_feature_spec",
        "build_initial_edge_feature_specs",
        "compute_ema_values",
        "compute_initial_edge_feature_bundle",
        "ema_warmup_bars",
        "materialize_initial_edge_features",
        "normalize_ema_lengths",
    }:
        from .features import (
            EDGE_FEATURE_KEYS,
            EDGE_FEATURE_VERSION,
            EMA_BAR_FINALIZATION,
            EMA_DTYPE,
            EMA_FEATURE_KEY,
            EMA_FEATURE_VERSION,
            EMA_SOURCE_FIELD,
            EMA_TIMING_SEMANTICS,
            EMA_WARMUP_MULTIPLIER,
            EdgeFeatureMaterializationConfig,
            build_ema_feature_spec,
            build_initial_edge_feature_specs,
            compute_ema_values,
            compute_initial_edge_feature_bundle,
            ema_warmup_bars,
            materialize_initial_edge_features,
            normalize_ema_lengths,
        )

        exports = {
            "EDGE_FEATURE_KEYS": EDGE_FEATURE_KEYS,
            "EDGE_FEATURE_VERSION": EDGE_FEATURE_VERSION,
            "EMA_BAR_FINALIZATION": EMA_BAR_FINALIZATION,
            "EMA_DTYPE": EMA_DTYPE,
            "EMA_FEATURE_KEY": EMA_FEATURE_KEY,
            "EMA_FEATURE_VERSION": EMA_FEATURE_VERSION,
            "EMA_SOURCE_FIELD": EMA_SOURCE_FIELD,
            "EMA_TIMING_SEMANTICS": EMA_TIMING_SEMANTICS,
            "EMA_WARMUP_MULTIPLIER": EMA_WARMUP_MULTIPLIER,
            "EdgeFeatureMaterializationConfig": EdgeFeatureMaterializationConfig,
            "build_ema_feature_spec": build_ema_feature_spec,
            "build_initial_edge_feature_specs": build_initial_edge_feature_specs,
            "compute_ema_values": compute_ema_values,
            "compute_initial_edge_feature_bundle": compute_initial_edge_feature_bundle,
            "ema_warmup_bars": ema_warmup_bars,
            "materialize_initial_edge_features": materialize_initial_edge_features,
            "normalize_ema_lengths": normalize_ema_lengths,
        }
        return exports[name]

    if name in {
        "build_event_overlay_id",
        "MVP_OVERLAY_DATASET_KINDS",
        "MVP_OVERLAY_VERSION",
        "build_overlay_id",
        "overlay_hit_test_priority",
        "overlay_z_order",
        "project_overlay_objects",
        "project_structure_event_overlay_objects",
        "sort_overlay_objects_for_render",
    }:
        from .overlays import (
            build_event_overlay_id,
            MVP_OVERLAY_DATASET_KINDS,
            MVP_OVERLAY_VERSION,
            build_overlay_id,
            overlay_hit_test_priority,
            overlay_z_order,
            project_overlay_objects,
            project_structure_event_overlay_objects,
            sort_overlay_objects_for_render,
        )

        exports = {
            "build_event_overlay_id": build_event_overlay_id,
            "MVP_OVERLAY_DATASET_KINDS": MVP_OVERLAY_DATASET_KINDS,
            "MVP_OVERLAY_VERSION": MVP_OVERLAY_VERSION,
            "build_overlay_id": build_overlay_id,
            "overlay_hit_test_priority": overlay_hit_test_priority,
            "overlay_z_order": overlay_z_order,
            "project_overlay_objects": project_overlay_objects,
            "project_structure_event_overlay_objects": project_structure_event_overlay_objects,
            "sort_overlay_objects_for_render": sort_overlay_objects_for_render,
        }
        return exports[name]

    if name in {
        "FEATURE_BUNDLE_BASE_COLUMNS",
        "LEG_BAR_FINALIZATION",
        "LEG_KIND_GROUP",
        "LEG_RULEBOOK_VERSION",
        "LEG_STRUCTURE_VERSION",
        "LEG_TIMING_SEMANTICS",
        "LegMaterializationConfig",
        "MAJOR_LH_BAR_FINALIZATION",
        "MAJOR_LH_KIND_GROUP",
        "MAJOR_LH_RULEBOOK_VERSION",
        "MAJOR_LH_STRUCTURE_VERSION",
        "MAJOR_LH_TIMING_SEMANTICS",
        "MajorLowerHighMaterializationConfig",
        "PIVOT_KIND_GROUP",
        "PIVOT_LEFT_WINDOW",
        "PIVOT_RIGHT_WINDOW",
        "PIVOT_RULEBOOK_VERSION",
        "PIVOT_STRUCTURE_VERSION",
        "PivotMaterializationConfig",
        "PivotScanResult",
        "StructureDependency",
        "build_feature_ref",
        "build_leg_structure_frame",
        "build_major_lh_structure_frame",
        "build_pivot_structure_frame",
        "build_structure_id",
        "build_structure_input_ref",
        "build_structure_ref",
        "compute_pivot_scan",
        "compute_pivot_scan_reference",
        "load_structure_dependency",
        "load_structure_inputs",
        "materialize_legs",
        "materialize_major_lh",
        "materialize_pivots",
    }:
        from .structures import (
            FEATURE_BUNDLE_BASE_COLUMNS,
            LEG_BAR_FINALIZATION,
            LEG_KIND_GROUP,
            LEG_RULEBOOK_VERSION,
            LEG_STRUCTURE_VERSION,
            LEG_TIMING_SEMANTICS,
            LegMaterializationConfig,
            MAJOR_LH_BAR_FINALIZATION,
            MAJOR_LH_KIND_GROUP,
            MAJOR_LH_RULEBOOK_VERSION,
            MAJOR_LH_STRUCTURE_VERSION,
            MAJOR_LH_TIMING_SEMANTICS,
            MajorLowerHighMaterializationConfig,
            PIVOT_KIND_GROUP,
            PIVOT_LEFT_WINDOW,
            PIVOT_RIGHT_WINDOW,
            PIVOT_RULEBOOK_VERSION,
            PIVOT_STRUCTURE_VERSION,
            PivotMaterializationConfig,
            PivotScanResult,
            StructureDependency,
            build_feature_ref,
            build_leg_structure_frame,
            build_major_lh_structure_frame,
            build_pivot_structure_frame,
            build_structure_id,
            build_structure_input_ref,
            build_structure_ref,
            compute_pivot_scan,
            compute_pivot_scan_reference,
            load_structure_dependency,
            load_structure_inputs,
            materialize_legs,
            materialize_major_lh,
            materialize_pivots,
        )

        exports = {
            "FEATURE_BUNDLE_BASE_COLUMNS": FEATURE_BUNDLE_BASE_COLUMNS,
            "LEG_BAR_FINALIZATION": LEG_BAR_FINALIZATION,
            "LEG_KIND_GROUP": LEG_KIND_GROUP,
            "LEG_RULEBOOK_VERSION": LEG_RULEBOOK_VERSION,
            "LEG_STRUCTURE_VERSION": LEG_STRUCTURE_VERSION,
            "LEG_TIMING_SEMANTICS": LEG_TIMING_SEMANTICS,
            "LegMaterializationConfig": LegMaterializationConfig,
            "MAJOR_LH_BAR_FINALIZATION": MAJOR_LH_BAR_FINALIZATION,
            "MAJOR_LH_KIND_GROUP": MAJOR_LH_KIND_GROUP,
            "MAJOR_LH_RULEBOOK_VERSION": MAJOR_LH_RULEBOOK_VERSION,
            "MAJOR_LH_STRUCTURE_VERSION": MAJOR_LH_STRUCTURE_VERSION,
            "MAJOR_LH_TIMING_SEMANTICS": MAJOR_LH_TIMING_SEMANTICS,
            "MajorLowerHighMaterializationConfig": MajorLowerHighMaterializationConfig,
            "PIVOT_KIND_GROUP": PIVOT_KIND_GROUP,
            "PIVOT_LEFT_WINDOW": PIVOT_LEFT_WINDOW,
            "PIVOT_RIGHT_WINDOW": PIVOT_RIGHT_WINDOW,
            "PIVOT_RULEBOOK_VERSION": PIVOT_RULEBOOK_VERSION,
            "PIVOT_STRUCTURE_VERSION": PIVOT_STRUCTURE_VERSION,
            "PivotMaterializationConfig": PivotMaterializationConfig,
            "PivotScanResult": PivotScanResult,
            "StructureDependency": StructureDependency,
            "build_feature_ref": build_feature_ref,
            "build_leg_structure_frame": build_leg_structure_frame,
            "build_major_lh_structure_frame": build_major_lh_structure_frame,
            "build_pivot_structure_frame": build_pivot_structure_frame,
            "build_structure_id": build_structure_id,
            "build_structure_input_ref": build_structure_input_ref,
            "build_structure_ref": build_structure_ref,
            "compute_pivot_scan": compute_pivot_scan,
            "compute_pivot_scan_reference": compute_pivot_scan_reference,
            "load_structure_dependency": load_structure_dependency,
            "load_structure_inputs": load_structure_inputs,
            "materialize_legs": materialize_legs,
            "materialize_major_lh": materialize_major_lh,
            "materialize_pivots": materialize_pivots,
        }
        return exports[name]

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
