from __future__ import annotations

__all__ = [
    "FEATURE_BUNDLE_BASE_COLUMNS",
    "LEG_BAR_FINALIZATION",
    "LEG_KIND_GROUP",
    "LEG_RULEBOOK_VERSION",
    "LEG_STRUCTURE_VERSION",
    "LEG_TIMING_SEMANTICS",
    "LegMaterializationConfig",
    "MAJOR_LH_BAR_FINALIZATION",
    "MAJOR_LH_KIND_GROUP",
    "MAJOR_LH_RULEBOOK_VERSION",
    "MAJOR_LH_STRUCTURE_VERSION",
    "MAJOR_LH_TIMING_SEMANTICS",
    "MajorLowerHighMaterializationConfig",
    "PIVOT_KIND_GROUP",
    "PIVOT_LEFT_WINDOW",
    "PIVOT_RIGHT_WINDOW",
    "PIVOT_RULEBOOK_VERSION",
    "PIVOT_STRUCTURE_VERSION",
    "PivotMaterializationConfig",
    "PivotScanResult",
    "StructureDependency",
    "StructureInputs",
    "build_feature_ref",
    "build_leg_structure_frame",
    "build_major_lh_structure_frame",
    "build_pivot_structure_frame",
    "build_structure_id",
    "build_structure_input_ref",
    "build_structure_ref",
    "compute_pivot_scan",
    "compute_pivot_scan_reference",
    "iter_structure_input_part_frames",
    "load_structure_dependency",
    "load_structure_inputs",
    "materialize_legs",
    "materialize_major_lh",
    "materialize_pivots",
    "structure_inputs_from_frames",
]


def __getattr__(name: str):
    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    from .ids import build_structure_id
    from .input import (
        FEATURE_BUNDLE_BASE_COLUMNS,
        StructureDependency,
        StructureInputs,
        build_feature_ref,
        build_structure_input_ref,
        build_structure_ref,
        iter_structure_input_part_frames,
        load_structure_dependency,
        load_structure_inputs,
        structure_inputs_from_frames,
    )
    from .legs import (
        LEG_BAR_FINALIZATION,
        LEG_KIND_GROUP,
        LEG_RULEBOOK_VERSION,
        LEG_STRUCTURE_VERSION,
        LEG_TIMING_SEMANTICS,
        LegMaterializationConfig,
        build_leg_structure_frame,
        materialize_legs,
    )
    from .major_lh import (
        MAJOR_LH_BAR_FINALIZATION,
        MAJOR_LH_KIND_GROUP,
        MAJOR_LH_RULEBOOK_VERSION,
        MAJOR_LH_STRUCTURE_VERSION,
        MAJOR_LH_TIMING_SEMANTICS,
        MajorLowerHighMaterializationConfig,
        build_major_lh_structure_frame,
        materialize_major_lh,
    )
    from .pivots import (
        PIVOT_KIND_GROUP,
        PIVOT_LEFT_WINDOW,
        PIVOT_RIGHT_WINDOW,
        PIVOT_RULEBOOK_VERSION,
        PIVOT_STRUCTURE_VERSION,
        PivotMaterializationConfig,
        PivotScanResult,
        build_pivot_structure_frame,
        compute_pivot_scan,
        compute_pivot_scan_reference,
        materialize_pivots,
    )

    exports = {
        "FEATURE_BUNDLE_BASE_COLUMNS": FEATURE_BUNDLE_BASE_COLUMNS,
        "LEG_BAR_FINALIZATION": LEG_BAR_FINALIZATION,
        "LEG_KIND_GROUP": LEG_KIND_GROUP,
        "LEG_RULEBOOK_VERSION": LEG_RULEBOOK_VERSION,
        "LEG_STRUCTURE_VERSION": LEG_STRUCTURE_VERSION,
        "LEG_TIMING_SEMANTICS": LEG_TIMING_SEMANTICS,
        "LegMaterializationConfig": LegMaterializationConfig,
        "MAJOR_LH_BAR_FINALIZATION": MAJOR_LH_BAR_FINALIZATION,
        "MAJOR_LH_KIND_GROUP": MAJOR_LH_KIND_GROUP,
        "MAJOR_LH_RULEBOOK_VERSION": MAJOR_LH_RULEBOOK_VERSION,
        "MAJOR_LH_STRUCTURE_VERSION": MAJOR_LH_STRUCTURE_VERSION,
        "MAJOR_LH_TIMING_SEMANTICS": MAJOR_LH_TIMING_SEMANTICS,
        "MajorLowerHighMaterializationConfig": MajorLowerHighMaterializationConfig,
        "PIVOT_KIND_GROUP": PIVOT_KIND_GROUP,
        "PIVOT_LEFT_WINDOW": PIVOT_LEFT_WINDOW,
        "PIVOT_RIGHT_WINDOW": PIVOT_RIGHT_WINDOW,
        "PIVOT_RULEBOOK_VERSION": PIVOT_RULEBOOK_VERSION,
        "PIVOT_STRUCTURE_VERSION": PIVOT_STRUCTURE_VERSION,
        "PivotMaterializationConfig": PivotMaterializationConfig,
        "PivotScanResult": PivotScanResult,
        "StructureDependency": StructureDependency,
        "StructureInputs": StructureInputs,
        "build_feature_ref": build_feature_ref,
        "build_leg_structure_frame": build_leg_structure_frame,
        "build_major_lh_structure_frame": build_major_lh_structure_frame,
        "build_pivot_structure_frame": build_pivot_structure_frame,
        "build_structure_id": build_structure_id,
        "build_structure_input_ref": build_structure_input_ref,
        "build_structure_ref": build_structure_ref,
        "compute_pivot_scan": compute_pivot_scan,
        "compute_pivot_scan_reference": compute_pivot_scan_reference,
        "iter_structure_input_part_frames": iter_structure_input_part_frames,
        "load_structure_dependency": load_structure_dependency,
        "load_structure_inputs": load_structure_inputs,
        "materialize_legs": materialize_legs,
        "materialize_major_lh": materialize_major_lh,
        "materialize_pivots": materialize_pivots,
        "structure_inputs_from_frames": structure_inputs_from_frames,
    }
    return exports[name]
